### ISSUE TITLE
maka-cli error on osx

### ISSUE THREAD

**Issue by rafahoro** [maka-io/maka-cli#4]
Hi, Im getting error when trying to use maka (first time user)
```
> nvm --version                                                     
0.35.3
> node --version                                                     
v12.16.1
> npm i -g @maka/maka-cli@latest
.....
s
> maka --help                                                     
internal/modules/cjs/loader.js:63
const internalModuleStat = function (f) { return require('fs').internalModuleStat(f); };
                                                               ^

TypeError: require(...).internalModuleStat is not a function
    at internalModuleStat (internal/modules/cjs/loader.js:63:64)
    at stat (internal/modules/cjs/loader.js:149:18)
    at Function.Module._findPath (internal/modules/cjs/loader.js:651:16)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:27)
    at Function.Module._load (internal/modules/cjs/loader.js:896:27)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1343:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:444:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:76:3)
    at internal/bootstrap/pkg.js:7:1
```
Same error with any other commande (--version,  maka install meteor)
Any idea whats wrong? Do I need to install something else ?

**Comment by rafahoro** [comment]
Uh, just found the answer in https://www.gitmemory.com/issue/aws-amplify/amplify-cli/6924/803460347 
Seems the issue is in VSCode (and NODE_OPTIONS). Running from the Terminal/console works

**Comment by maka-io** [comment]
Hey @rafahoro !  Thanks for checking out Maka-Cli! That is an interesting error.  I'm glad you were able to get past it, but i'll look into any way of handling that error in a more useful manner 😃

**Comment by rafahoro** [comment]
> Hey @rafahoro ! Thanks for checking out Maka-Cli! That is an interesting error. I'm glad you were able to get past it, but i'll look into any way of handling that error in a more useful manner 😃

Great. Just for completeness, this is my VsCode version.
```
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

And this when I run in VsCode integrated terminal:
```
> echo $NODE_OPTIONS                           
--require "/Users/myUser/Library/Application Support/Code/User/workspaceStorage/a25273f13cf13cba149b1d0f8ccdcccb/ms-vscode.js-debug/bootloader.js" 
```
